### ISSUE TITLE
Questions about formulas in the code

### ISSUE THREAD

**Issue by Finnhh** [int8/monte-carlo-tree-search#16]
Hi, thanks for ur contribution. I have two questions about the formulas in the code.

**Q1**: Why UCT = (c.q / c.n) + c_param * np.sqrt((2 * np.log(self.n) / c.n)), not (c.q / c.n) + c_param * np.sqrt((np.log(self.n) / c.n)), I feel confused on '2*'. Why is there this factor?
https://github.com/int8/monte-carlo-tree-search/blob/8e3ef9a2c31841f8dc984c642a14dfe3bb1d62ec/mctspy/tree/nodes.py#L62

**Q2**: Why q = wins - loses, not q = wins? Why need to sub loses? I'm a little confused, hope your guidance.
[https://github.com/int8/monte-carlo-tree-search/blob/8e3ef9a2c31841f8dc984c642a14dfe3bb1d62ec/mctspy/tree/nodes.py#L89
![image](https://user-images.githubusercontent.com/20140308/212006433-5e3e15b5-0fa0-47ff-83ef-d652fd2ce040.png)](https://github.com/int8/monte-carlo-tree-search/blob/8e3ef9a2c31841f8dc984c642a14dfe3bb1d62ec/mctspy/tree/nodes.py#L87-L89)

Looking forward to your reply.

**Comment by int8** [comment]
Hello - it's been some time - I basically replicated the code from this tutorial - algorithm (2) http://www.incompleteideas.net/609%20dropbox/other%20readings%20and%20resources/MCTS-survey.pdf [page 9] 

you can try to look for this particular constant justification in that document
