### ISSUE TITLE
How to run your code?

### ISSUE THREAD

**Issue by sasforce** [int8/monte-carlo-tree-search#5]
Hi,I till confused about the program, how to run it? I had inputted all the code in README file but it didn't work. Is the code you supply down there not completed for running the entire game? Thank you

**Comment by int8** [comment]
can you please provide more details? Please just copy and paste the error you get

**Comment by int8** [comment]
you need to make sure you have python3 installed + numpy 
`pip install numpy`

**Comment by UPedrou** [comment]
Hi, I am also trying to execute the program. I input all the code in the readme file but when I executed, the mouse cursor change to a cross and after that, this error message appears: 
import: not authorized `np' @ error/constitute.c/WriteImage/1028.
from: can't read /var/mail/mcts.nodes
from: can't read /var/mail/mcts.search
from: can't read /var/mail/games.tictactoe
./test.py: line 6: syntax error near unexpected token `('
./test.py: line 6: `state = np.zeros((3,3))'

How can I execute the program? Thank you

**Comment by int8** [comment]
it works fine, please make sure you have python3, numpy and you run the code from the inside of repository dir
