### ISSUE TITLE
New Game

### ISSUE THREAD

**Issue by atanas1054** [int8/monte-carlo-tree-search#8]
Hey,

I want to have a 2-player game where they take turns. In the beginning there are 114 possible actions and they decrease by 1 every time a player makes a move. The game is played for 10 turns (that's the terminal state). I have my own function for the reward.

Here is a sample game tree:

START- available actions to both players -> [1,2,3,4,5,6....112,113,114]
Player 1 - takes action 5 -> [5,0,0,0,0,0,0,0,0,0] -remove action 5 from available actions
Player 2 - takes action 32->[5,0,0,0,0,32,0,0,0,0] - remove action 32 from the available actions
Player 1- takes action 97 ->[5,97,0,0,0,32,0,0,0,0] - remove action 97 from the available actions
Player 2 takes action 56 -> [5,97,0,0,0,32,56,0,0,0] - remove action 56 from the available actions
....
Final (example) game state after each player makes 5 actions -> [5,97,3,5,1,32,56,87,101,8]
First 5 entries present the actions taken by Player1, second 5 entries present the actions taken by Player 2

Finally, I apply a reward function to this vector [5,97,3,5,1,32,56,87,101,8]
I want to be able to give the initial game state and whose turn it is to move. Any help will be appreciated.

**Comment by int8** [comment]
Hi @atanas1054 

what about something along these lines: 

```python 
import numpy as np
from mctspy.games.common import TwoPlayersAbstractGameState, AbstractGameAction


class YourGameAction(AbstractGameAction):
    def __init__(self, chosen_value):
        self.chosen_value = chosen_value

class YourGameState(TwoPlayersAbstractGameState):

    def __init__(self, internal_state, next_to_move=1):
        if len(state.shape) != 2 or state.shape[0] != state.shape[1]:
            raise ValueError("Only 2D square boards allowed")
        self.internal_state = internal_state # e.g. [5,97,3,5,1,32,56,87,101,8]
        self.next_to_move = next_to_move

    @property
    def game_result(self):
        return evaluate(self.internal_state)

    def is_game_over(self):
        return self.game_result is not None

    def is_move_legal(self, move):
        # implement it 
        pass 

    def move(self, move):
        new_internal_state = update_internal_state(self.internal_state, move) 
        return YourGameState(new_internal_state, -next_to_move) # change who moves next 

    def get_legal_actions(self):
        return array_of_legal_actions() # with elements of type YourGameAction
```

**Comment by int8** [comment]
although 114 actions seems to be a high branching factor - not sure if your memory will make it...
